### ISSUE TITLE
How to get verifier code to get access token

### ISSUE THREAD

**Issue by anchitjindal91** [sammyrulez/beatport-api#1]
Hi i am referring  your code for my app i want to know from i will get the code in following
final OauthHolder auth = authService.auth(code ,authorizationKey); in sample it is just '123', I tried many thing but it give me following error
 org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '{"metadata":{"error":"Access Denied","message":"Invalid oauth verifier: '1234'","request":{}},"results":[]}. Please help me to sort this out. 

Thanks

**Comment by sammyrulez** [comment]
if you provide an invalid code/authorizationKey you'll get an exception. By design. If you provide full stack trace I can make the exception text more easy to read.

**Comment by anchitjindal91** [comment]
Thanks, for your reply above is the only error return. One more thing can you please tell me is your code work for non web application? Or do we need to use Direct Access Token api for non web apps as described in API doc.

**Comment by sammyrulez** [comment]
I have used it in integration test from a non web application. So Yes it should work.

**Comment by anchitjindal91** [comment]
ok thanks but still my question is from where i will get val of code e.g (authService.auth(_code_ ,authorizationKey)) that is used get authorization? You mention in the doc "user must visit this link in orther to obtain the activation code" i visit but there is no parameter with name code. So i am not clear about it :(
